# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5a87a4bebe324ceca10e841fa917812e1c7a258a29b7edac946308b6aef8b6930f79e4781da352787938aff9d4fb0f97a1658febc55c4f297ab16ea206ae0a6f

test:
  secret_key_base: d142f77258c3d8f6153593d12411e359acf0753dc251efc825a7d3454907e5ae2c90f96c80bebca24a2f9e8878ec5dd2fe32a8bc69668cfc25902efba2700553

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
